version: '3.8'

services:

  minio:
    image: minio/minio:latest
    container_name: foodapp-minio
    restart: unless-stopped
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - foodapp-network

volumes:
  mongodb_data:
  minio_data:

networks:
  foodapp-network:
    driver: bridge
